test:
	$(MAKE) -C test1_import $@
	$(MAKE) -C test2_import_non_existing_source_file $@
	$(MAKE) -C test3_import_with_dependency $@
	$(MAKE) -C test4_import_deleted $@
	$(MAKE) -C test_add_uuids_1 $@
	$(MAKE) -C test_add_uuids_2_multiple_tasks $@
	$(MAKE) -C test_add_uuids_3_multiple_files $@

clean:
	$(MAKE) -C test1_import $@
	$(MAKE) -C test2_import_non_existing_source_file $@
	$(MAKE) -C test3_import_with_dependency $@
	$(MAKE) -C test4_import_deleted $@
	$(MAKE) -C test_add_uuids_1 $@
	$(MAKE) -C test_add_uuids_2_multiple_tasks $@
	$(MAKE) -C test_add_uuids_3_multiple_files $@
