name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install taskwarrior
      run: |
        sudo apt-get update
        sudo apt-get install -y taskwarrior

    - name: Install ripgrep
      run: |
        sudo apt-get install -y ripgrep

    - name: Run tests
      run: |
        cd tests
        make test

